### ISSUE TITLE
Node service crashes when entering GitHub user ID

### ISSUE THREAD

**Issue by darwinz** [wuufeii/followers-following#1]
After starting the node service and the UI, the node service crashes when entering my GitHub user ID, due to the following error:

```
/projects/followers-following/node/routes/followers.js:18
      let stars = body.split(`https://github.com/${params.name}?tab=stars`)[1].split('</span>')[0].split('<span')[1].split('>')[1]
                                                                              ^

TypeError: Cannot read properties of undefined (reading 'split')
    at Request._callback (/Users/brandonjohnson/Projects/followers-following/node/routes/followers.js:18:79)
    at Request.self.callback (/Users/brandonjohnson/Projects/followers-following/node_modules/request/request.js:185:22)
    at Request.emit (node:events:527:28)
    at Request.<anonymous> (/Users/brandonjohnson/Projects/followers-following/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:527:28)
    at IncomingMessage.<anonymous> (/Users/brandonjohnson/Projects/followers-following/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:641:28)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by wuufeii** [comment]
Because the html structure returned by github has changed, you can intercept it according to the specific structure.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wuufeii/followers-following"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月24日(星期五) 下午2:26
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[wuufeii/followers-following] Node service crashes when entering GitHub user ID (Issue #1)





 
After starting the node service and the UI, the node service crashes when entering my GitHub user ID, due to the following error:
 /projects/followers-following/node/routes/followers.js:18       let stars = body.split(`https://github.com/${params.name}?tab=stars`)[1].split('</span&gt;')[0].split('<span')[1].split('&gt;')[1]                                                                               ^ TypeError: Cannot read properties of undefined (reading 'split')     at Request._callback (/Users/brandonjohnson/Projects/followers-following/node/routes/followers.js:18:79)     at Request.self.callback (/Users/brandonjohnson/Projects/followers-following/node_modules/request/request.js:185:22)     at Request.emit (node:events:527:28)     at Request.<anonymous&gt; (/Users/brandonjohnson/Projects/followers-following/node_modules/request/request.js:1154:10)     at Request.emit (node:events:527:28)     at IncomingMessage.<anonymous&gt; (/Users/brandonjohnson/Projects/followers-following/node_modules/request/request.js:1076:12)     at Object.onceWrapper (node:events:641:28)     at IncomingMessage.emit (node:events:539:35)     at endReadableNT (node:internal/streams/readable:1345:12)     at processTicksAndRejections (node:internal/process/task_queues:83:21)
